### PR TITLE
Fix issues on GKE

### LINKED ISSUE #279: Kafka Operator doesn't work on Google Kubernetes Engine (and probably most other managed k8s offerings)
There are two issues that keep the Kafka operator from working properly on managed k8s (probably, but definitely tested on GKE).

1. Persistent Volumes are not writeable by the stackable user inside of our containers, as these belong to root and have` rwxr-xr-x` permisions set.
2. Kafka complains about the `lost+found` folder in its data directory, which is autocreated here by ext4 since when using a persistentvolume this is the root of that volume.

### PR DESCRIPTION
**Pull request by soenkeliebau**
The default logs.dir for Kafka is moved to a subdirectory of the volume mount, as Kafka is troubled by the presence of the "lost+found" folder which resides in the root dir.

Added an init container to chown the data directory to the Stackable user.

fixes #279

## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

File: rust/operator/src/kafka_controller.rs [hunk 1]
```diff
@@ -370,6 +371,29 @@ fn build_broker_rolegroup_statefulset(
...
         .add_volume_mount("tmp", "/stackable/tmp")
         .build();
+
+    // For most storage classes the mounts will belong to the root user and not be writeable to
+    // other users.
+    // Since kafka runs as the user stackable inside of the container the data directory needs to be
+    // chowned to that user for it to be able to store data there.
+    let mut container_chown = ContainerBuilder::new("chown-data")
+        .image(&image)
+        .command(vec!["/bin/bash".to_string(), "-c".to_string()])
```
Comment (teozkr) [inline rust/operator/src/kafka_controller.rs:381]:
```suggestion
        .command(vec!["/bin/bash".to_string(), "-euo".to_string(), "pipefail".to_string(), "-c".to_string()])
```

**Review by teozkr — APPROVED** [review]

**Comment by teozkr** [comment]
The rustfmt gods are fickle indeed

**Comment by soenkeliebau** [comment]
> The rustfmt gods are fickle indeed

they are harsh masters ..
